### ISSUE TITLE
Computer integration

### ISSUE THREAD

**Issue by cobra** [cobra/ImmersiveEngineering#1]
implement support for TEs
- [x] Arc Furnace CC
- [x] Arc Furnace OC
- [x] Crusher CC
- [x] Crusher OC
- [x] Diesel Generator CC
- [x] Diesel Generator OC
- [x] Current Transformer CC
- [x] Current Transformer OC
- [x] Excavator CC
- [x] Excavator OC
- [x] Refinery CC
- [x] Refinery OC
- [x] Core Sample Drill CC
- [x] Core Sample Drill OC
- [x] Floodlight CC
- [x] Floodlight OC
- [x] Fermenter CC
- [x] Fermenter OC
- [x] Squeezer CC
- [x] Squeezer OC
- [x] Assembler CC
- [x] Assembler OC
- [x] Bottling Machine CC
- [x] Bottling Machine OC

ideas and implementation needed:

general rework for some TEs 
- [x] Current Transformer: move logic from block to TE class
- [x] Core Sample Drill: move logic from block to TE class
- [x] Arc Furnace: replace redstone control by computer control
- [x] Crusher: replace redstone control by computer control
- [x] Diesel Generator: replace redstone control by computer control
- [x] Excavator: replace redstone control by computer control
- [x] Refinery: replace redstone control by computer control
- [x] Floodlight: replace redstone control by computer control
- [x] Floodlight: limit changes by computers to something like once per second

general tasks
- [ ] unify machine names
- [x] unify command names
- [x] define feature set for machines
- [x] documentation for commands
- [ ] getLocation command returning where this machine is sitting(?)

ComputerCraft related:
- [x] make sides of some blocks solid, needed for modems to get attached
- [x] allow connections to certain multiblock blocks only

OpenComputers related:
- [x] investigate why the generator isn't connecting properly at all times

**Comment by malte0811** [comment]
I figured out why OC compat wasn't working for me: I had expected the OC team to upload the deobf jar to curseforge along with their normal download like most other mods I use in my dev environment. Since there was no "deobf" download, I used the normal version, which worked fine and works fine for CC as well. but their class transformer or something apparently didn't like that and buggered up your peripheral implementations. It's working now since I found the link to the "deobf" version in their github readme file

**Comment by cobra** [comment]
Floodlight (wired, powered) on top of a CC computer, after a world reload. I wrapped and used it before reloading, but not afterwards. Wanted to tear down the test setup, broke the floodlight first and crashed:

```
[15:15:11] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@4facb382:
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_66]
    at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_66]
    at blusunrize.immersiveengineering.common.EventHandler.onWorldTick(EventHandler.java:251) ~[EventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_129_EventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:712) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) [IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
```

**Comment by malte0811** [comment]
I'll be away until Sunday and won't be working on IE during that time, but if you ping me on GitHub, I will (probably) answer.
Also, [yay for 2k Additions!](https://github.com/BluSunrize/ImmersiveEngineering/compare/master...cobra:computerCompat)

**Comment by malte0811** [comment]
@cobra, I think I can close this now.
Also, Blu wants to do a release, only thing missing are your computer fixes (the ones you talked about on IRC yesterday). How important are those/how soon can you push them?

**Comment by malte0811** [comment]
@cobra when are you going to push the commit for shifting the slot id's in OC compat? If you don't want to push (or can't for some reason), I could redo those changes pretty easily.
